TheBlog/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Body { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
    }
}

TheBlog/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheBlog.Models;

namespace TheBlog.Controllers
{
    public class CommentsController : Controller
    {
        // GET: Comments
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs("GET")]
        public ActionResult Create(int pid)
        {
            return View(new Comment() { PostID = pid });
        }

        [AcceptVerbs("POST")]
        public ActionResult Create(Comment p)
        {
            p.Id = IncrementId();
            p.Name = (Session["user"] as User).Username.ToString();
            p.Date = DateTime.Now.ToString();
            p.UserID = Singleton.GetUser((Session["user"] as User).Username).Id;

            Singleton.models.Comments.Add(p);
            Singleton.models.SaveChanges();
            return RedirectToAction("See", "Posts", new { id = p.PostID });
        }

        [AcceptVerbs("GET")]
        public ActionResult Edit(int id)
        {
            return View(Singleton.models.Comments.FirstOrDefault(x => x.Id == id));
        }

        [AcceptVerbs("POST")]
        public ActionResult Edit(Comment c)
        {
            Comment temp = Singleton.GetComment(c.Id);
            string body = c.Body;
            c = temp;
            c.Body = body;

            Singleton.models.Comments.Remove(temp);
            Singleton.models.SaveChanges();
            Singleton.models.Comments.Add(c);
            Singleton.models.SaveChanges();
            return RedirectToAction("See", "Posts", new { id = c.PostID });
        }

        public ActionResult Delete(int id)
        {
            Comment c = Singleton.GetComment(id);
            int postId = c.PostID;

            Singleton.models.Comments.Remove(c);
            Singleton.models.SaveChanges();
            return RedirectToAction("See", "Posts", new { id = postId });
        }

        private int IncrementId()
        {
            if (Singleton.models.Comments.Count() > 0)
            {
                return Singleton.models.Comments.Max(x => x.Id) + 1;
            }
            else
            {
                return 0;
            }
        }
    }
}

TheBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheBlog.Models;

namespace TheBlog.Controllers
{
    public class PostsController : Controller
    {
        // GET: Posts
        public ActionResult Index()
        {
            IEnumerable<Post> posts = from post in Singleton.models.Posts orderby post.Date descending select post;
            ViewBag.IsAdmin = IsAdmin;
            return View(posts);
        }

        public ActionResult Update(int? id, string title, string body, DateTime dateTime)
        {
            if (!IsAdmin)
            {
                return RedirectToAction("Index");
            }

            Post post = GetPost(id);
            post.Title = title;
            post.Body = body;
            post.Date = dateTime;

            if (!id.HasValue)
            {
                Singleton.models.Posts.Add(post);
            }
            Singleton.models.SaveChanges();

            return RedirectToAction("Index");
        }

        [AcceptVerbs("GET")]
        public ActionResult Edit(int? id)
        {
            Post post = GetPost(id);
            return View(post);
        }

        [AcceptVerbs("POST")]
        public ActionResult Edit(Post p)
        {
            Post temp = GetPost(p.Id);
            p.UserId = temp.UserId;
            Singleton.models.Posts.Remove(temp);
            Singleton.models.Posts.Add(p);

            Singleton.models.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            Singleton.models.Posts.Remove(GetPost(id));
            Singleton.models.SaveChanges();
            return RedirectToAction("Index");
        }

        [AcceptVerbs("GET")]
        public ActionResult Create()
        {

            Post p = new Post();
            return View(p);
        }

        [AcceptVerbs("POST")]
        public ActionResult Create(Post p)
        {
            p.Id = IncrementId();
            p.UserId = Singleton.GetUser((Session["user"] as User).Username.ToString()).Id;

            Singleton.models.Posts.Add(p);
            Singleton.models.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult See(int? id)
        {
            Post p = GetPost(id);
            if (p.Id != -1)
            {
                Session["poster"] = Singleton.GetUser(p.UserId).Username;
                return View(p);
            }
            return RedirectToAction("Index");
        }

        private int IncrementId()
        {
            if (Singleton.models.Posts.Count() > 0)
            {
                return Singleton.models.Posts.Max(x => x.Id) + 1;
            }
            else
            {
                return 0;
            }
        }

        private Post GetPost(Post p)
        {
            return Singleton.models.Posts.Where(x => x.Equals(p)).First();
        }

        private Post GetPost(int? id)
        {
            return id.HasValue ? Singleton.models.Posts.Where(x => x.Id == id).First() : new Post() { Id = -1 };
        }

        public bool IsAdmin { get { return true; /* Session["IsAdmin"] != null && (bool)Session["IsAdmin"]; */ } }
    }
}

TheBlog/Views/Posts/Create.cshtml
@model TheBlog.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm(new { title = Model.Title, date = DateTime.Now, body = Model.Body }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TheBlog/Views/Posts/Edit.cshtml
@model TheBlog.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(new { id = Model.Id, title = Model.Title, date = Model.Date, body = Model.Body }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TheBlog/Views/Posts/Index.cshtml
@using TheBlog.Models;
@model IEnumerable<Post>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    @Styles.Render("~/Content/blog.css")
    @Scripts.Render("~/Scripts/blog.js")
</head>
<body>
    
    <article id="holder" style="position: absolute; top: 70px; left: 0; text-align:center; width:100%">
        


        <div id="posts">
            
                
                
            <form style="display:inline" id="form" method="get">
                @if (Session["User"] != null)
                {
                    <section class="post" style="font-size:100px;text-align:center;">@Html.ActionLink("+", "Create")</section>
                }
                @foreach (var item in Model)
                {
                    <section id="@Html.DisplayFor(modelItem => item.Id)" class="post" onclick="selectedPost(this)">
                        @Html.DisplayFor(modelItem => item.Title)
                        <div class="content">@Html.DisplayFor(modelItem => item.Body)</div>

                        <footer>
                            <small>
                                made by @Html.DisplayFor(modelItem => item.User.Username)
                                <div>@((DateTime.Now - item.Date).Minutes) minutes ago</div>
                            </small>
                        </footer>
                    </section>

                }
            </form>
        </div>
    </article>
</body>
</html>

TheBlog/Views/Posts/See.cshtml
@model TheBlog.Models.Post

@{
    ViewBag.Title = "See";
}
@using TheBlog.Models;
@using TheBlog.Controllers;
<!DOCTYPE html>
<html>
<head>
<script>
    var holder;

    window.onload = function () {
        document.getElementById(@Html.DisplayFor(modelItem => modelItem.Id)).style.height =
                (window.innerHeight - 200) + 'px';

        adjustments();
    }

    window.onresize = adjustments;

    function adjustments() {
        if (window.innerWidth <= 550) {
            if (document.getElementById('holder')) {
                holder = document.getElementById('holder');
                document.getElementById("header").removeChild(holder);
                document.getElementById("header").children[0].style.float = 'none';
            }
        }
        else {
            if (!document.getElementById('holder')) {
                document.getElementById("header").appendChild(holder);
                document.getElementById("header").children[0].style.float = 'left';

            }
        }
    }

</script>
</head>
<body style="background-color: #044170">

    <article style="position: absolute; top: 70px; left: 0; text-align:center; width:100%">


        <div id="currentPost" style="position:fixed;top: 50px; padding-top:50px; width: 100%; left:0;text-align:center; height: 100%;">
            <div style="position:absolute; top:8px;right:0">
                <form method="get">
                    @if (Session["IsAdmin"] != null || (Session["User"] != null && Model.UserId == Singleton.GetUser((Session["User"] as User).Username).Id))
                    {
                        <input id="edit" formaction="/Posts/Edit/@Html.DisplayFor(model => model.Id)" type="submit" class="controls" value="Edit" />
                        <input id="delete" formaction="/Posts/Delete/@Html.DisplayFor(model => model.Id)" type="submit" class="controls" value="Delete" />

                    }
                    <input type="submit" class="controls" style="margin-right:16px" formaction="/Posts/Index" value="X" />
                </form>

                
            </div>
            <section id="@Html.DisplayFor(modelItem => modelItem.Id)" class="currentPost">
                @Html.DisplayFor(modelItem => modelItem.Title)
                Posted by @Session["poster"]
                <div class="content">@Html.DisplayFor(modelItem => modelItem.Body)</div>
                <footer>created at @Html.DisplayFor(modelItem => modelItem.Date)</footer>
                
                <!-- Comments on post-->
                <ul class="comments">
                    @if (Session["User"] != null)
                    {
                        <li class="comment">
                            <div style="text-align: center; font-weight: bold; font-size: 110px">
                                @Html.ActionLink("+", "Create", "Comments", new { pid = Model.Id }, null)
                            </div>
                        </li>
                    }

                    @foreach (var comment in Model.Comments)
                    {
                        <li class="comment">
                            @if (Session["User"] != null && (comment.UserID == Singleton.GetUser((Session["User"] as User).Username).Id || Session["IsAdmin"] != null))
                            {
                                <div style="text-align: right">
                                    <button class="controls" style="height:18px; font-size:10px; margin-bottom: 4px;">@Html.ActionLink("edit", "Edit", "Comments", new { id = comment.Id }, new { })</button>
                                    <button class="controls" style="height:18px; font-size:10px; margin-bottom: 4px;">@Html.ActionLink("delete", "Delete", "Comments", new { id = comment.Id }, new { })</button>
                                </div>
                            }
                            <div class="content">
                                @Html.Raw(comment.Body.ToString())
                            </div>

                            

                            <footer>-@Html.Raw(comment.Name.ToString())</footer>
                        </li>
                    }
                </ul>

            </section>
        </div>

        <!--p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p-->
    </article>
</body>
</html>